# -*- coding: utf-8 -*-
"""task7_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HpK0Dp0ROZTnz-SPQ4rVm5mocsUPFq43
"""

def check_input(element):
    """
    Проверяет, является ли элемент строкой.

    Параметры:
    element: любой элемент

    Возвращает:
    bool: True, если элемент - строка, иначе False
    """
    return isinstance(element, str)


def get_substring(s):
    """
    Находит самую длинную подстроку без повторяющихся символов.

    Параметры:
    s (str): входная строка

    Возвращает:
    str: самая длинная подстрока без повторений
    """
    if not s:
        return ""

    # Используем скользящее окно
    char_index = {}  # Словарь для хранения последних позиций символов
    start = 0  # Начало текущей подстроки
    max_length = 0  # Максимальная длина найденной подстроки
    result = ""  # Результат

    for i, char in enumerate(s):
        # Если символ уже встречался и его позиция >= start,
        # значит он в текущей подстроке, нужно сдвинуть start
        if char in char_index and char_index[char] >= start:
            start = char_index[char] + 1

        # Обновляем позицию символа
        char_index[char] = i

        # Проверяем, не стала ли текущая подстрока длиннее
        current_length = i - start + 1
        if current_length > max_length:
            max_length = current_length
            result = s[start:i+1]

    return result


def main(lst):

    longest_str = ""
    longest_str_index = -1

    for i, element in enumerate(lst):
        if check_input(element):
            if longest_str_index == -1 or len(element) > len(longest_str):
                longest_str = element
                longest_str_index = i

    if longest_str_index != -1:
        substring = get_substring(longest_str)
    else:
        substring = ""

    print(f"{longest_str_index}, '{substring}'")

